apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions, Sentry, AWS Lambda.
  annotations:
    github.com/project-slug: organisation/github-project-slug
    jira/project-key: TEST
    jira/component: COMP
    # aws.com/lambda-function-name: HelloWorld
    # aws.com/lambda-region: eu-west-1
    # # jenkins.io/github-folder: 'roadiehq/sample-service'
    # sentry.io/project-slug: sample-service
    # argocd/app-name: guestbook
    # snyk.io/org-name: roadie
spec:
  type: service
  owner: roadie
  lifecycle: experimental
  providesApis:
    - sample-service