# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: zip-demo
  title: Scaffolder-utils test template
  description: An example template to test most of the scaffolder-utils actions
spec:
  owner: roadie
  type: service

  parameters:
    - title: Create File
      properties:
        path:
          title: Path
          type: string
          description: workspace path to zip
          ui:autofocus: true
          ui:options:
            rows: 5
        content:
          title: File Content
          type: string
          description: content of the file
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Sleep
      properties:
        amount:
          title: Sleep
          type: number
          description: Amount to sleep in seconds

    - title: Append
      properties:
        path:
          title: Path
          type: string
          description: Amount to sleep in seconds
        content:
          title: Content
          type: string
          description: This will be appended to the end of the file

    - title: Zip
      properties:
        zipPath:
          title: Path
          type: string
          default: "."
          description: workspace path to zip
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: createFile
      name: Create File
      action: roadiehq:utils:fs:write
      input:
        path: ${{ parameters.path }}
        content: ${{ parameters.content }}

    - id: sleep
      name: Sleep
      action: roadiehq:utils:sleep
      input:
        amount: ${{ parameters.amount }}

    - id: appendFile
      name: Append File
      action: roadiehq:utils:fs:append
      input:
        path: ${{ parameters.path }}
        content: ${{ parameters.content }}

    - id: zip
      name: Zip
      action: roadiehq:utils:zip
      input:
        path: ${{ parameters.zipPath }}

  output:
    path: ${{ steps.zip.output.path }}
