apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions, Sentry, AWS Lambda.
  annotations:
    github.com/project-slug: organisation/github-project-slug
    aws.com/lambda-function-name: HelloWorld
    aws.com/lambda-region: eu-west-1
    jira/project-key: TEST
    jira/component: COMP
    datadoghq.com/dashboard-url: https://p.datadoghq.eu/sb/test-datadog-link
    datadoghq.com/graph-token: qwertytoken1234
spec:
  type: service
  owner: roadie
  lifecycle: experimental
  providesApis:
    - sample-service

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-2
  description: |
    A service for testing Travis CI plugin
  annotations:
    travis-ci.com/repo-slug: RoadieHQ/sample-service
spec:
  type: service
  owner: roadie
  lifecycle: experimental
  providesApis:
    - sample-service-2
