name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: '0'
      
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc

      - name: Run test
        run: yarn test

  publish-packages:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish packages
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: |
        lerna version patch
        lerna publish --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}