name: E2E Test On PR

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: test
    
    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build static site
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./packages/app