name: E2E Test On PR

on:
  workflow_run:
    workflows: ["Bump versions"]
    types:
      - completed
  [push]:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
    
    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
         fetch-depth: '0'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: 'http://localhost:3000'
          project: ./packages/app
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
  package-update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose