name: publish
on:
  push:
    branches:
      - main
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org/'
    
    - name: Ensure access
      run: npm whoami --registry https://registry.npmjs.org/
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    
    - name: Config git user
      run: |
        git config --global user.name "roadie-bot"
        git config --global user.email "bot@roadie.io"
    
    - run: yarn install
    - run: yarn tsc
    - run: yarn build
    
    - name: Run publish
      run: lerna publish from-package --yes --no-verify-access
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
