name: Check bump versions
on:
  schedule:
  - cron: "0 6 * * 5"
  push:
  pull_request:
   types: [opened, synchronize, reopened, closed]


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Run weekly
      uses: actions/checkout@v2
      with:
       fetch-depth: '0'
      
    - name: Install dependencies
      run: |
        yarn install
        yarn backstage-cli versions:bump